
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sppdahhxkzsxvvgnbnqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwcGRhaGh4a3pzeHZ2Z25ibnFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MDUwNjYsImV4cCI6MjA1OTE4MTA2Nn0.0TYzgAPGg57f6ug9ByfLlaJE9Sad3tm9AY_K7HHnz38";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
